export { default as anakhImg1 } from '../assets/anakhronos/images/gallery/anakhronos/ABIR.png';
export { default as anakhImg2 } from '../assets/anakhronos/images/gallery/anakhronos/GALLERY1.jpg';
export { default as anakhImg3 } from '../assets/anakhronos/images/gallery/anakhronos/GALLERY10.jpg';
export { default as anakhImg4 } from '../assets/anakhronos/images/gallery/anakhronos/GALLERY13.jpg';
export { default as anakhImg5 } from '../assets/anakhronos/images/gallery/anakhronos/GALLERY2.jpeg';
export { default as anakhImg6 } from '../assets/anakhronos/images/gallery/anakhronos/GALLERY3.jpeg';
export { default as anakhImg7 } from '../assets/anakhronos/images/gallery/anakhronos/GALLERY4.jpg';
export { default as anakhImg8 } from '../assets/anakhronos/images/gallery/anakhronos/GALLERY6.jpg';
export { default as anakhImg9 } from '../assets/anakhronos/images/gallery/anakhronos/HOMESLIDER1.jpeg';
export { default as anakhImg10 } from '../assets/anakhronos/images/gallery/anakhronos/HOMESLIDER2.jpeg';
export { default as anakhImg11 } from '../assets/anakhronos/images/gallery/anakhronos/HOMESLIDER3.jpeg';
export { default as anakhImg12 } from '../assets/anakhronos/images/gallery/anakhronos/RIDDLES.png';
export { default as anakhImg13 } from '../assets/anakhronos/images/gallery/anakhronos/SF2.jpg';
export { default as anakhImg14 } from '../assets/anakhronos/images/gallery/anakhronos/SINGER.jpeg';
export { default as anakhImg15 } from '../assets/anakhronos/images/gallery/anakhronos/SLIDERA 1.jpg';
export { default as anakhImg16 } from '../assets/anakhronos/images/gallery/anakhronos/SLIDERA 3.jpg';
export { default as anakhImg17 } from '../assets/anakhronos/images/gallery/anakhronos/SLIDERA 4.jpg';
export { default as anakhImg18 } from '../assets/anakhronos/images/gallery/anakhronos/SLIDERA 5.jpg';
export { default as anakhImg19 } from '../assets/anakhronos/images/gallery/anakhronos/SLIDERA 8.jpg';
export { default as anakhImg20 } from '../assets/anakhronos/images/gallery/anakhronos/STEPUP1.jpg';
export { default as anakhImg21 } from '../assets/anakhronos/images/gallery/anakhronos/STEPUP2.jpg';
export { default as anakhImg22 } from '../assets/anakhronos/images/gallery/anakhronos/SURTARANG.jpg';
export { default as anakhImg23 } from '../assets/anakhronos/images/gallery/anakhronos/GALLERY7.JPG';
export { default as anakhImg24 } from '../assets/anakhronos/images/gallery/anakhronos/GALLERY8.JPG';
export { default as anakhImg25 } from '../assets/anakhronos/images/gallery/anakhronos/GALLERY9.JPG';
export { default as anakhImg26 } from '../assets/anakhronos/images/gallery/anakhronos/GALLERY11.JPG';
export { default as anakhImg27 } from '../assets/anakhronos/images/gallery/anakhronos/GALLERY12.JPG';
export { default as anakhImg28 } from '../assets/anakhronos/images/gallery/anakhronos/gallery_fresher4.JPG';
export { default as anakhImg29 } from '../assets/anakhronos/images/gallery/anakhronos/SLIDERA9.JPG';
export { default as arrow } from '../assets/anakhronos/images/gallery/anakhronos/arrow.png';
export { default as anakhronosMegaEvent } from '../assets/anakhronos/ANAKHRONOS_MEGA_EVENT.png';
export { default as prarambhMegaEvent } from '../assets/anakhronos/PRARAMBH_MEGA_EVENT.JPG';
