export { default as logo } from '../assets/anakhronos/images/yo.png';
export { default as tmslLogo } from '../assets/anakhronos/images/tmsl-logo.png';
export { default as eventImg } from '../assets/anakhronos/images/ana/img-3.jpg';
export { default as eventImgBg } from '../assets/anakhronos/images/events_bg.jpg';
export { default as Prarambh } from '../assets/anakhronos/images/Prarambh.png';
export { default as anakhronosLogoText } from '../assets/anakhronos/Anakhronos 2023 Logo.png';
export { default as gallimg1 } from '../assets/anakhronos/images/gallery/GALLERY1.jpg';
export { default as gallimg2 } from '../assets/anakhronos/images/gallery/GALLERY2.jpg';
export { default as gallimg3 } from '../assets/anakhronos/images/gallery/GALLERY3.jpg';
export { default as gallimg4 } from '../assets/anakhronos/images/gallery/GALLERY4.jpg';
export { default as gallimg5 } from '../assets/anakhronos/images/gallery/GALLERY5.jpg';
export { default as gallimg6 } from '../assets/anakhronos/images/gallery/GALLERY6.jpg';
export { default as gallimg7 } from '../assets/anakhronos/images/gallery/GALLERY7.JPG';
export { default as gallimg8 } from '../assets/anakhronos/images/gallery/GALLERY8.JPG';
export { default as gallimg9 } from '../assets/anakhronos/images/gallery/GALLERY9.JPG';
export { default as gallimg10 } from '../assets/anakhronos/images/gallery/GALLERY10.jpg';
export { default as gallimg11 } from '../assets/anakhronos/images/gallery/GALLERY11.jpg';
export { default as gallimg12 } from '../assets/anakhronos/images/gallery/GALLERY12.jpg';
export { default as gallimg13 } from '../assets/anakhronos/images/gallery/GALLERY13.jpg';
export { default as gallimg14 } from '../assets/anakhronos/images/gallery/gallery_anakhronos.jpg';
export { default as gallimg15 } from '../assets/anakhronos/images/gallery/gallery_anakhronos1.JPG';
export { default as gallimg16 } from '../assets/anakhronos/images/gallery/gallery_anakhronos2.jpg';
export { default as gallimg17 } from '../assets/anakhronos/images/gallery/gallery_fresher.jpg';
export { default as gallimg18 } from '../assets/anakhronos/images/gallery/gallery_fresher1.JPG';
export { default as gallimg19 } from '../assets/anakhronos/images/gallery/gallery_fresher2.jpeg';
export { default as gallimg20 } from '../assets/anakhronos/images/gallery/gallery_fresher3.jpeg';
export { default as gallimg21 } from '../assets/anakhronos/images/gallery/gallery_fresher4.jpeg';
export { default as gallimg22 } from '../assets/anakhronos/images/gallery/gallery_fresher5.JPG';
export { default as gallimg23 } from '../assets/anakhronos/images/gallery/gallery_fresher6.jpeg';
export { default as gallimg24 } from '../assets/anakhronos/images/gallery/gallery_fresher7.jpeg';
export { default as gallimg26 } from '../assets/anakhronos/images/gallery/gallery_fresher8.jpeg';
export { default as gallimg25 } from '../assets/anakhronos/images/gallery/gallery_fresher9.JPG';
export { default as gallimg27 } from '../assets/anakhronos/images/gallery/GUITAR1.jpg';
export { default as arrow } from '../assets/anakhronos/images/gallery/arrow.png';

export { default as facebookLogo } from '../assets/anakhronos/images/icons8-facebook.svg';
export { default as instagramLogo } from '../assets/anakhronos/images/icons8-instagram(1).svg';
export { default as twitterlogo } from '../assets/anakhronos/images/icons8-twitter.svg';
export { default as youtubelogo } from '../assets/anakhronos/images/icons8-youtube.svg';

export { default as ankuranLogo } from '../assets/anakhronos/images/ankuran-logo.png';
export { default as yoLogo } from '../assets/anakhronos/images/yo.png';
export { default as aboutImg } from '../assets/anakhronos/images/about-us.jpg';
export { default as technoImg } from '../assets/anakhronos/images/techno.jpg';
export { default as nestleLogo } from '../assets/anakhronos/images/nestle.png';
export { default as chevroletLogo } from '../assets/anakhronos/images/chevrolet.png';
export { default as olaCabLogo } from '../assets/anakhronos/images/Ola_Cabs_logo.png';
export { default as timesOfIndiaLogo } from '../assets/anakhronos/images/times_of_india.png';
export { default as Britannia_Industries_Logo } from '../assets/anakhronos/images/Britannia_Industries_Logo.png';
export { default as friends_fm } from '../assets/anakhronos/images/friends_fm.png';
export { default as Hoichoi_logo } from '../assets/anakhronos/images/Hoichoi-Logo.png';
export { default as pepsi_logo } from '../assets/anakhronos/images/pepsi-logo.png';
export { default as Hero_logo } from '../assets/anakhronos/images/hero-logo.png';
export { default as Chowman_logo } from '../assets/anakhronos/images/chowman_logo.png';
export { default as Haldirams_logo } from '../assets/anakhronos/images/Haldirams_Logo.png';
export { default as HyattRegency_logo } from '../assets/anakhronos/images/hyatt-regency.png';
export { default as Monster_Logo } from '../assets/anakhronos/images/Monster-Logo.png';
export { default as PNB_Logo } from '../assets/anakhronos/images/punjab-national-bank.png';
export { default as Selvel_logo } from '../assets/anakhronos/images/selvel-logo.png';
export { default as Svf_logo } from '../assets/anakhronos/images/svf-logo.png';
export { default as TooYumm_logo } from '../assets/anakhronos/images/Too_Yumm_logo.png';
export { default as Webel_logo } from '../assets/anakhronos/images/Webel-logo.png';
export { default as CTVN } from '../assets/anakhronos/images/CTVN.png';
export { default as Stadel_logo } from '../assets/anakhronos/images/Stadel.png';
export { default as T2 } from '../assets/anakhronos/images/T2.png';
export { default as Nexa } from '../assets/anakhronos/images/Nexa.png';
export { default as Red_FM } from '../assets/anakhronos/images/RED_FM_logo.png';
export { default as Aniket } from '../assets/anakhronos/images/aniket.png';
export { default as Keshav } from '../assets/anakhronos/images/keshav.png';
export { default as Yesh } from '../assets/anakhronos/images/yesh.png';
export { default as Evan } from '../assets/anakhronos/images/evan.png';
export { default as Chandan } from '../assets/anakhronos/images/chandan.png';
export { default as Rudrajit } from '../assets/anakhronos/images/rudra.png';
export { default as Sahel } from '../assets/anakhronos/images/sahel.png';
export { default as Somya } from '../assets/anakhronos/images/somya.png';
export { default as Abhijeet } from '../assets/anakhronos/images/abhijeet.png';
export { default as Suchetana } from '../assets/anakhronos/images/suchetana.png';
export { default as Soham } from '../assets/anakhronos/images/soham.png';
export { default as Bidyayan } from '../assets/anakhronos/images/bidyayan.png';
export { default as Oishi } from '../assets/anakhronos/images/oishi.png';
export { default as Hrishav } from '../assets/anakhronos/images/hrishav.png';
export { default as Iman } from '../assets/anakhronos/images/Iman.png';
export { default as Dhruba } from '../assets/anakhronos/images/dhruba.png';
export { default as Pratyush } from '../assets/anakhronos/images/pratyush.png';
export { default as Shatavisha } from '../assets/anakhronos/images/shatavisha.png';
export { default as ADutta } from '../assets/anakhronos/images/adutta.png';
export { default as Punjay } from '../assets/anakhronos/images/punjay.png';
export { default as Agnish } from '../assets/anakhronos/images/agnish.png';
export { default as Nabanita } from '../assets/anakhronos/images/nabanita.png';
export { default as Bishal } from '../assets/anakhronos/images/bishal.png';
export { default as Sourajit } from '../assets/anakhronos/images/soura.png';
export { default as Abir } from '../assets/anakhronos/images/abir1.png';
export { default as Arpita } from '../assets/anakhronos/images/arpita.png';
export { default as Asen } from '../assets/anakhronos/images/asen.png';

export { default as Maam } from '../assets/anakhronos/images/maam.jpeg';
export { default as Meghdut } from '../assets/anakhronos/images/Meghdut.jpeg';
export { default as Avijit } from '../assets/anakhronos/images/Avijit Kar.jpeg';

export { default as blurherobg } from '../assets/anakhronos/images/BLURBG.jpg';

export { default as GroupMerchandise } from '../assets/anakhronos/images/Merchandise_image.png';

export { default as AbhijeetBhattacharya } from '../assets/anakhronos/images/Abhijeet.jpg';
export { default as Lopamudra } from '../assets/anakhronos/images/Lopamudra.jpg';
export { default as Cactus } from '../assets/anakhronos/images/Cactus.jpg';
export { default as Chandrabindu } from '../assets/anakhronos/images/Chandrabindu.jpg';
export { default as Jojo } from '../assets/anakhronos/images/Miss Jojo.jpg';
export { default as Nachiketa } from '../assets/anakhronos/images/Nachiketa.jpg';
export { default as Fossils } from '../assets/anakhronos/images/Fossils.jpg';
export { default as Anjan_dutta } from '../assets/anakhronos/images/Anjan_dutta.jpg';
export { default as Anushka_manchanda } from '../assets/anakhronos/images/Anushka_manchanda.jpg';
export { default as Armaan_malik } from '../assets/anakhronos/images/Armaan_malik.jpg';
export { default as Ash_king } from '../assets/anakhronos/images/Ash_king.jpg';
export { default as Benny_dayal } from '../assets/anakhronos/images/Benny_dayal.jpg';
export { default as Dev_negi } from '../assets/anakhronos/images/Dev_negi.jpg';
export { default as Fakira } from '../assets/anakhronos/images/Fakira.jpg';
export { default as Indian_ocean } from '../assets/anakhronos/images/Indian_ocean.jpg';
export { default as Javed_ali } from '../assets/anakhronos/images/Javed_ali.jpg';
export { default as Jonita_gandhi } from '../assets/anakhronos/images/Jonita_gandhi.jpg';
export { default as KK } from '../assets/anakhronos/images/KK.jpg';
export { default as Krosswindz } from '../assets/anakhronos/images/Krosswindz.jpg';
export { default as kunal_ganjawala } from '../assets/anakhronos/images/kunal_ganjawala.jpg';
export { default as Milind_gaba } from '../assets/anakhronos/images/Milind_gaba.jpg';
export { default as Msonic } from '../assets/anakhronos/images/Msonic.jpg';
export { default as Muhammed_Irfan } from '../assets/anakhronos/images/Muhammed_Irfan.jpg';
export { default as Parikrama } from '../assets/anakhronos/images/Parikrama.jpg';
export { default as Prithibi } from '../assets/anakhronos/images/Prithibi.jpg';
export { default as Raeth } from '../assets/anakhronos/images/Raeth.jpg';
export { default as Raghu_dixit } from '../assets/anakhronos/images/Raghu_dixit.jpg';
export { default as Riddles } from '../assets/anakhronos/images/Riddles.jpg';
export { default as Rupankar } from '../assets/anakhronos/images/Rupankar.jpg';
export { default as Shaan } from '../assets/anakhronos/images/Shaan.jpg';
export { default as usha_uttup } from '../assets/anakhronos/images/usha_uttup.jpg';
export { default as Vishal_dadlani } from '../assets/anakhronos/images/Vishal_dadlani.jpg';

export { default as TWOMINS2FAME } from '../assets/anakhronos/images/2MINS2FAME.jpg';
export { default as ARTANDCRAFT } from '../assets/anakhronos/images/ART AND CRAFT.jpg';
export { default as BANDBOX } from '../assets/anakhronos/images/BANDBOX.jpg';
export { default as CLUBFEET } from '../assets/anakhronos/images/CLUBFEET.png';
export { default as IMPRESSION } from '../assets/anakhronos/images/IMPRESSION.jpeg';
export { default as PANACHE } from '../assets/anakhronos/images/PANACHE.jpg';
export { default as SHORTFILMMAKING } from '../assets/anakhronos/images/SHORTFILMMAKING.jpeg';
export { default as STEPUP } from '../assets/anakhronos/images/STEPUP.jpeg';
export { default as SURTARANG } from '../assets/anakhronos/images/SURTARANG.jpeg';

export { default as DANCETECHNODANCE } from '../assets/anakhronos/images/DANCE TECHNO DANCE.jpg';
export { default as FRESHERART } from '../assets/anakhronos/images/FRESHERART.jpg';
export { default as FRESHERPHOTOGRAPHY } from '../assets/anakhronos/images/FRESHERPHOTOGRAPHY.jpg';
export { default as MRMISSFRESHER } from '../assets/anakhronos/images/MR MISS FRESHER.jpg';
export { default as TECHNOIDOL } from '../assets/anakhronos/images/TECHNO IDOL.jpg';